config/routes.rb
AbeMail::Application.routes.draw do

  resources :users, only: [:create]
  resource :session, only: [:create, :destroy, :new]
  resources :messages, only: [:create, :show, :update] do
    collection do
      post "outgoing"
      get 'inbox'
      get 'sent'
      get 'favorited'
      get 'draft'
      get 'trash'
    end
  end
  resources :flags, only: [:update]
  resources :chats, only: [:index, :create]

  root :to => "messages#inbox"

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :draft, :sender, :sender_id, :subject, :recipient_emails
  # allowing :recipients here lets you created the nested model?
  before_save :format_recipient_emails
  after_save :create_receiver_flags

  #after_initialize :set_internal_user_id


  #switch this so all come in as an array and are hadnled in the model

  has_many(
    :recipients,
    class_name: "Recipient",
    foreign_key: :message_id,
    primary_key: :id,
    inverse_of: :message
  )

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :sender_id,
    primary_key: :id
  )

  has_many(
    :flags,
    class_name: "Flag",
    foreign_key: :message_id,
    primary_key: :id,
    inverse_of: :message
  )

  def time_stamp
    self.created_at.strftime( self.created_at.today? ?  '%l:%M %p' : '%b %d' )
  end

  def sent_by?(user_id)
    self.sender_id == user_id
  end

  def preview
    self.body.squeeze.slice(0, (150 - self.subject.length))
  end

  def set_internal_user_id
    return if self.sender_id
    user = User.find_by_email(self.sender)
    user && self.sender_id = user.id
  end

  def format_recipient_emails
    self.recipient_emails.gsub!(/\s+/m, ';')
    self.recipient_emails += ';' unless self.recipient_emails.ends_with?(';')
    self.recipient_emails.prepend(';') unless self.recipient_emails.starts_with?(';')
  end

  def display_recipient_emails
    self.recipient_emails.gsub(';', ', ').slice(2..-3) # a better way to do this?
  end

  def create_receiver_flags #use a lambda here?
    self.recipient_emails.split(';').slice(1..-1).each do |email|
      internal_user = User.find_by_email(email)
      if internal_user && (internal_user.id != self.sender_id) #needs testing
        self.flags.create(user_id: internal_user.id)
      end
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_current_user!
  respond_to  :json, :html


  def outgoing #do this in a transaction??
    imply_sender

    @message = Message.new(params[:message])

    @message.flags.build(user_id: current_user.id)

    if @message.save

      Abemailer.outgoing(@message).deliver! unless internal_only?

      redirect_to inbox_messages_url #update for backbone
    else
      render json: @message.errors.full_messages
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def inbox
    @messages = current_user.inbox
    @users = User.where('id != ?', current_user.id)
    @background = "ocean"

    respond_to do |format|
      format.html { render :index }
      format.json { respond_with(@messages) }
    end
  end


  def sent
    @messages = current_user.sent

    respond_with(@messages)
  end

  def favorited
    @messages = current_user.favorited

    respond_with(@messages)
  end

  def trash
    @messages = current_user.trash

    respond_with(@messages)
  end



end

app/helpers/messages_helper.rb
module MessagesHelper

  def imply_sender
    params[:message][:sender_id] = current_user.id
    params[:message][:sender] = current_user.email
  end

  def internal_only?
    @message.recipient_emails.split(";").map(&:strip).slice(1..-1).all? do |email|
      email.ends_with?('@abemail.net')
    end #use a lambda here?
  end


end

app/views/messages/_chat.html.erb
<h2>AbeChat </h2>
 <ul id="chat-log">

 </ul>
 <form class="new-chat" action="<%= chats_url %>" method="post" data-remote="true">
   <p><input type="text" name="chat_text" id="chat-text" autocomplete="off" placeholder="Type here, press enter to send"></p>
   <input type="hidden" name="chat_to" value="" id="chat_to">
   
 </form>

app/views/messages/_email_box.html.erb
<table class="emails" border="1">
  <% @messages.each do |message| %>

    <%= render partial: 'email_row', locals: { message: message } %>

  <% end %>
</table>

app/views/messages/_email_row.html.erb
<tr class="<%= "unread" unless message.flags.first.read %>">
      <td class="check">
        <input type="checkbox" name="selector[]" value="" id="selector[]">
      </td>
      <td class="heart  <%= "red" if message.flags.first.heart %>">
        <div class="heart-box">
        <%= link_to '&hearts;'.html_safe, flag_url(message.flags.first), method: :put %>
        </div>
      </td>

      <% if message.sent_by?(current_user.id) %>
        <td class="to">TO: <%= message.display_recipient_emails %></td>
      <% else %>
        <td class="from"><%= message.sender %></td>
      <% end %>


      <td class="preview">
       <a href="<%= message_url(message)%>">
         <%= render partial: 'message_preview', locals: { message: message }%>
        </a>
      </td>
      <td class="time-tag">
        <%= time_tag(message.created_at, format: message.created_at.today? ?  '%l:%M %p' : '%b %d') %>
      </td>

    </tr>

app/views/messages/_message_preview.html.erb
<span>
  <!-- <marquee> -->
  <% if message.subject.length > 0 %>
  <span class="bold"><%= message.subject %> - </span>
  <% end %>
  <%= message.preview %>
  <!-- </marquee> -->
</span>

app/views/messages/_new_email.html.erb
<div id="new-email-wrap">
  <h2>New Message</h2>
  <form action="<%= outgoing_messages_path %>" method="post">
    <%= render partial: "layouts/authenticity" %>
    <div id="email-inputs">
    <input type="text" name="message[recipient_emails]" placeholder="to" id="new-to">
    <input type="text" name="message[subject]" id="new-subject" placeholder="subject">
    <textarea name="message[body]" id="message[body]" rows="23">
      <%= ("&#13;" *5).html_safe %>From, &#13; <%= current_user.name  %>
    </textarea>
    </div>
    <p><input type="submit" value="Send &rarr;"></p>
  </form>
</div>

app/views/messages/_option_buttons.html.erb
<ul class="buttons">
	<li id="select">Select
		<ul class="buttons dropdown">
			<li id="all">All</li>
			<li id="none">None</li>
		</ul>
	</li>
	
  <li id="compose">Compose</li>
	<li id="trash">Trash</li>
  <li id="read">Read/Unread</li>
  <li id="heart">Toggle Favorite</li>
</ul>

app/views/messages/_sidebar.html.erb
<ul class="buttons">

  <% inbox_count = @messages.count( %>
    <% conditions: "flags.read = false AND messages.sender_id != #{current_user.id}", %>
    <% include: :flags %>
  <% )  %>
  <li><%= link_to "Inbox", '/#' + inbox_messages_path%></li>
  <li><%= link_to "Favorited", '/#' + favorited_messages_path%></li>
  <li><%= link_to "Sent", '/#' + sent_messages_path%></li>
  <li><%= link_to "Trash", '/#' + trash_messages_path%></li>
</ul>

app/views/messages/index.html.erb
<section  id="menu">
  <%= render :partial => 'option_buttons' %>
</section>

<section id="main" class="group">


  <section class="group" id="sidebar">
    <%= render :partial => 'sidebar' %>
    <br>
    
    <ul id="contacts">
			<h2>AbeChat</h2>
      <% @users.each do |user| %>
      <li><%= user.name %></li>
      <% end %>
    </ul>
  </section>

  <section id="mailbox">

  

  </section>
</section>

<section id="new-email" class="invisible drag-me">
<%= render partial: "new_email" %>
</section>

<section id="chat" class="invisible drag-me">
	
  <%= render :partial => 'chat' %>
</section>


<input type="hidden" id="user_id" value="<%= current_user.id %>">

<script type="application/javascript" charset="utf-8" id="bootstrap-inbox">
  <%= render(file: 'messages/inbox.rabl', object: @messages, formats: :rabl).html_safe %>
</script>



<script src="http://js.pusher.com/2.1/pusher.min.js"></script>

<script>
	var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>');
</script>

app/views/messages/show.html.erb
<h1><%= @message.subject %></h1>
<ul>
  <li><%= @message.sender %></li>
  <li>to:<%= @message.display_recipient_emails %></li>
  <li><%= @message.body %></li>
</ul>