config/routes.rb
AbeMail::Application.routes.draw do

  resources :users, only: [:create]
  resource :session, only: [:create, :destroy, :new]
  resources :messages, only: [:create, :show, :update] do
    collection do
      post "outgoing"
      get 'inbox'
      get 'sent'
      get 'favorited'
      get 'draft'
      get 'trash'
    end
  end
  resources :flags, only: [:update]
  resources :chats, only: [:index, :create]

  root :to => "messages#inbox"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
  attr_reader :password

  validates :password_hash, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :name, :email, :session_token, :presence => true
  validates :email, uniqueness: true

  validates :email, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, before: :create }

  after_initialize :ensure_session_token

  before_create :downcase_email

  has_many :flags

  has_many(
    :sent_messages,
    class_name: "Message",
    foreign_key: :sender_id,
    primary_key: :id
  )

  has_many(
    :recipients,
    class_name: "Recipient",
    foreign_key: :recipient_id,
    primary_key: :id
  )


  has_many :received_messages, through: :recipients, source: :message

  

  def sent #use a lambda here?
    self.sent_messages.includes(:flags).merge(Flag.where(user_id: self.id, trashed: false)).sort_by { |m| m.created_at }
  end

  def inbox
    q_email = "%;#{self.email}%"
    sent_messages = Message.where("recipient_emails like ?", q_email)
    sent_messages.includes(:flags).merge(Flag.where(user_id: self.id, trashed: false)).sort_by { |m| m.created_at }
  end

  def favorited
    Message.includes(:flags).merge(Flag.where(user_id: self.id, heart: true, trashed: false)).sort_by { |m| m.created_at }
  end
  #save the m.created at to a prc
  def trash
    Message.includes(:flags).merge(Flag.where(user_id: self.id, trashed: true)).sort_by { |m| m.created_at }
  end


  def downcase_email
    self.email.downcase!
  end


  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_hash).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_hash = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

    private
    def ensure_session_token
      self.session_token ||= self.class.generate_session_token
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


   def create
     validate_extension

     @user = User.new(params[:user])

     if @user.save
       self.current_user = @user
       redirect_to inbox_messages_url
     else
       render :json => @user.errors.full_messages
     end
   end



end

app/views/users/_new_user.html.erb
<form class="login invisible" action="<%= users_url %>" method="post">
<h1>Sign Up</h1>

  <%= render :partial => 'layouts/authenticity' %>
  <div class="inputs">
	  
	

	  <label>Email
		  <br>
	  <input
	     id="user_email"
	     name="user[email]"
	     type="text"
	     placeholder="@abemail.net">
	     
	  </label>
	

	  <label>Password
		  <br>
	  <input
	     id="user_password"
	     name="user[password]"
	     type="password"
	     placeholder="Password">
	 </label>
	 

	  <label> Verify
		  <br>
	  <input
	     id="user_password"
	     name="user[password]"
	     type="password"
	     placeholder="Same as above">
	  </label>
	  
	  <label>Name
		  <br>
	  <input
	     id="user_name"
	     name="user[name]"
	     type="text"
	     placeholder="Who are you?">
	 </label>
  </div>
  
	<div class="submit">
		<input type="submit" value="Sign Up">
	</div>
</form>